server:
  port: 8080

app:
  media:
    root-dir: ./generated-images    # 생성 이미지 저장 폴더(프로젝트 루트 기준)
    url-prefix: /media/             # 정적 서빙 URL 접두사
  characters:
    root-dir: ./base-characters     # 기본 캐릭터 PNG 폴더(루트 기준)

openai:
  # VM 옵션(-Dopenai.api-key) → 환경변수(OPENAI_API_KEY) → 없으면 빈값
  api-key: ${OPENAI_API_KEY:}
