server:
  port: 8080

 # env 파일 못읽어서 추가
spring:
  config:
    import: optional:file:.env[.properties]

app:
  media:
    root-dir: ./generated-images    # 생성 이미지 저장 폴더(프로젝트 루트 기준)
    url-prefix: /media/             # 정적 서빙 URL 접두사
  characters:
    location: classpath:character   # ← src/main/resources/character 를 의미

openai:
  # VM 옵션(-Dopenai.api-key) → 환경변수(OPENAI_API_KEY) → 없으면 빈값
  # api-key: ${openai.api-key:${OPENAI_API_KEY:}}
  api-key: ${OPENAI_API_KEY:}
