server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  media:
    root-dir: ./generated-images    # 생성 이미지 저장 폴더(프로젝트 루트 기준)
    url-prefix: /media/             # 정적 서빙 URL 접두사
  characters:
    root-dir: ./base-characters     # 기본 캐릭터 PNG 폴더(루트 기준)

openai:
  api-key: ${OPENAI_API_KEY:}        # 비어있으면 분석 스킵 가능
  api-url: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini

spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.share.dairy.service.diary_analysis: DEBUG

youtube:
  api-key: ${AIzaSyCd4xSQTWTi9EhP4A6RHt7anA0g5vIlijE:}
  region: KR
  max-results: 8
